clean:
	make -C bitcount clean
	make -C stringsearch clean
	make -C coremark clean
	make -C dhrystone clean
	make -C sha clean
	make -C crc32 clean
	make -C quick_sort clean
	make -C bubble_sort clean
	make -C select_sort clean
	make -C stream_copy clean
